spring.application.name=mini-twitter-api

# H2
spring.datasource.url=jdbc:h2:mem:minitwitter
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=mini-twitter-local-development-secret-key-must-be-long-enough-for-hs256
jwt.access-token-expiration-millis=3600000